repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: bash -c "cd backend && uv run ruff check ."
        language: system
        types: [python]

      - id: black
        name: black
        entry: bash -c "cd backend && uv run black ."
        language: system
        types: [python]